-- Idempotent: safe to run multiple times in MariaDB
ALTER TABLE `al_exam_submissions`
	ADD COLUMN IF NOT EXISTS `result_1` VARCHAR(5) DEFAULT NULL AFTER `subject_1`,
	ADD COLUMN IF NOT EXISTS `result_2` VARCHAR(5) DEFAULT NULL AFTER `subject_2`,
	ADD COLUMN IF NOT EXISTS `result_3` VARCHAR(5) DEFAULT NULL AFTER `subject_3`,
	ADD COLUMN IF NOT EXISTS `agreed_to_publish` TINYINT(1) DEFAULT 0,
	ADD COLUMN IF NOT EXISTS `results_submitted_at` TIMESTAMP NULL DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `exam_year` INT(11) DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `district_rank` INT(11) DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `island_rank` INT(11) DEFAULT NULL;
